### PR TITLE
Set Allowed DropDataTypes and File Extensions

### PR DESCRIPTION
**Pull request by getBoolean**
Add DropDataType.file to allow dropping any file
Support restricting what types of DropDataType and file extensions can be dropped

```dart
NativeDropView(
  allowedDropDataTypes: const <DropDataType>[
    DropDataType.image,
  ],
  allowedDropFileExtensions: const <String>[
    'epub',
    'apk',
  ],
  ...
```

Dropping is allowed when the dropping session contains an item that conforms to one of the `allowedDropDataTypes` OR when the file extension is included in `allowedDropFileExtensions`

I see that you've made some commits since I started working which has caused some conflicts. Let me know if you need me to resolve them.

### CODE REVIEW

**Comment by alexrabin** [comment]
Looks amazing! Thank you!

**Comment by getBoolean** [comment]
Theres an error after merging.

DropDataType and DropData need to be removed from drop_view_controller.dart and `file` needs to be added to DropDataType in drop_data.dart

Also the example package has errors after merging.

**Comment by alexrabin** [comment]
@getBoolean Yep I fixed it. Working on a new example app and will publish new version soon.

**Comment by getBoolean** [comment]
Thanks!

**Comment by alexrabin** [comment]
@getBoolean Updated to [v0.0.2](https://pub.dev/packages/native_drag_n_drop/changelog) Thanks for all your help!

**Pull request merged**
