### PR TITLE
Hopefully fixed the image and the text bug without breaking anything else

### PR DESCRIPTION
**Pull request by alexrabin**
Should fix issue #7 and #8

ezgif com-gif-maker 3

### CODE REVIEW

**Comment by alexrabin** [comment]
@getBoolean can you look this over please?

**Comment by getBoolean** [comment]
I am able to drop text from notes if I have file allowed and nothing else

```swift
else if isFile(item) && !item.itemProvider.canLoadObject(ofClass: NSURL.self) && !item.itemProvider.canLoadObject(ofClass: String.self)
```

I think that would be fixed if those two extra checks (isNotURL and isNotString) you added are moved inside isFIle(item)

**Comment by alexrabin** [comment]
@getBoolean I thought that's what you wanted? When file is only specified don't save text as a file. That check prevents that

**Comment by getBoolean** [comment]
> @getBoolean I thought that's what you wanted? When file is only specified don't save text as a file. That check prevents that

Yea it does work. The only problem now is that text is always allowed to be dropped in the can drop method when only files should be droppable. We should prevent all drops unless the drop has at least one allowed item.

The fix you already did is for when receiveNonAllowedItems is true (which means it will receive all dropped items as long as there is one item that is allowed). With your fix it properly recognizes it as a text in the perform drop method.

My suggested fix for it allowing text to be dropped when only file is enabled didn't work, i'll look into it more.

**Comment by alexrabin** [comment]
@getBoolean okay. Feel free to pull the branch and commit

**Comment by getBoolean** [comment]
> @getBoolean okay. Feel free to pull the branch and commit

It looks like strings conform to data, that's why it's accepted in the can handle method

**Pull request merged**
