### PR TITLE
Fix Dropping Bugs

### LINKED ISSUE #4: Able To Drop Non Allowed Items
Problem:
It is possible to drop items that have not been allowed as long as one item in the drop session is allowed

image

Proposed solution:
In the handle drop method, check the item if it conforms to an allowed type identifier or file extension. Code from the can drop method should be pulled into private functions so it can be reused (if possible).

### PR DESCRIPTION
**Pull request by getBoolean**
Closes #4

Added a boolean flag to allow non-allowed items to be dropped if at least one item in the dropping session was allowed
Fixed a potential bug where files such as PDF would be categorized as DropDataType.pdf even if only DropDataType.file was allowed
Fixed a bug where documents (.numbers) dropped from iCloud would not be accepted
Refactor code to be more readable

### CODE REVIEW

**Comment by getBoolean** [comment]
There are quite a lot of functions. I tried to keep it reasonable, let me know if you want it changed in any way.

**Comment by alexrabin** [comment]
Holy moly 😂 looks good to me. Can you provide a video so I can see if your changes worked?

**Comment by alexrabin** [comment]
Also can you test the pdf potential bug that you mentioned. Just want to make sure pdf's still return correctly

**Comment by getBoolean** [comment]
> Also can you test the pdf potential bug that you mentioned. Just want to make sure pdf's still return correctly

Old
image

New
image

**Comment by getBoolean** [comment]
> Holy moly 😂 looks good to me. Can you provide a video so I can see if your changes worked? 

image

**Comment by alexrabin** [comment]
> image

Oh I see what you did. I guess this works. I was imagining disabling the option to even drop items if the drop items contained invalid data types. Because I could see users complaining how some of their files aren't being added even though the green "plus" icon is showing

**Comment by getBoolean** [comment]
As for the iCloud one, it wasn't accepting .numbers files from iCloud, but it would it was stored locally. It was fixed by adding isDocument(item), which checks if the item conforms to UTI kUTTypeContent. 

https://web.archive.org/web/20190621082935/https://developer.apple.com/documentation/mobilecoreservices/uttype/uti_abstract_types

According to apple's docs, it will allow containing "document content". That is: documents, pasteboard data, and document packages. I am not sure how to test pasteboard data and document packages, because this would also allow that.

**Comment by alexrabin** [comment]
Good stuff. Correct me if I'm wrong but is the `isDocument()` and `isCompositeDocument()` the exact same code?

**Comment by getBoolean** [comment]
> Good stuff. Correct me if I'm wrong but is the `isDocument()` and `isCompositeDocument()` the exact same code?

You're right, isCompositeDocument() should be checking kUTTypeCompositeContent instead.

At the time I thought that it meant some type of zipped file. I just checked the latest documentation and it looks like compositeContent conforms to UTTypeContent, so its probably the same here. I'll remove that code.

**Comment by alexrabin** [comment]
> > image
> 
> Oh I see what you did. I guess this works. I was imagining disabling the option to even drop items if the drop items contained invalid data types. Because I could see users complaining how some of their files aren't being added even though the green "plus" icon is showing

Do you think it's a good idea to deny the drop completely if there is a data type that isn't allowed? I'm just worried about the user experience

**Comment by getBoolean** [comment]
Unfortunately I can't access the details for kUTTypeCompositeContent on the wayback machine, do you know where else I can find the apple documentation archive?

**Comment by alexrabin** [comment]
Are you referring to what all the uttypes are? https://developer.apple.com/documentation/uniformtypeidentifiers/uttype/system_declared_uniform_type_identifiers

The compositeContent is in there

**Comment by getBoolean** [comment]
> > > image
> > 
> > 
> > Oh I see what you did. I guess this works. I was imagining disabling the option to even drop items if the drop items contained invalid data types. Because I could see users complaining how some of their files aren't being added even though the green "plus" icon is showing
> 
> Do you think it's a good idea to deny the drop completely if there is a data type that isn't allowed? I'm just worried about the user experience

I think that would be best, it would be up to the programmer to add what files they support. I checked with Apple Books and it looks like they do it the same way.

**Comment by getBoolean** [comment]
> Are you referring to what all the uttypes are? https://developer.apple.com/documentation/uniformtypeidentifiers/uttype/system_declared_uniform_type_identifiers
> 
> The compositeContent is in there

The constant names are different than the ones in MobileCoreServices for iPadOS 11. I just wanted to make sure they didn't change something else.

**Comment by alexrabin** [comment]
> > > > image
> 
> > > 
> 
> > > 
> 
> > Do you think it's a good idea to deny the drop completely if there is a data type that isn't allowed? I'm just worried about the user experience
> 
> 
> 
> I think that would be best, it would be up to the programmer to add what files they support. I checked with Apple Books and it looks like they do it the same way.

I don't think we are on the same page. Your fix has it so if you have a video and an image and only the video is accepted you can hover over the drop view with the image and video, the green plus button will still show up even though when you drop the video and image, only the video will be accepted. It should be if there is a data type that isn't accepted then it doesn't allow any of the files to be dropped

The green plus button is confirmation that all files will be accepted. So if there is an unallowed file in the mix it should deny all of them

**Comment by getBoolean** [comment]
> 

You are right, I just checked with apple books and it sends all files as long as one item is acceptable. It's up to the app to show the user that one of the files was not an acceptable type. It would be best to remove the check for each item if its allowed in the perform drop method.

If you want, we can also have a boolean flag to reject the drop if it has any nonaccepted files, but I don't think that's needed since I don't think it would be a good user experience either if the user knows they selected something that should be able to be dropped

**Comment by alexrabin** [comment]
Okay so we'll leave it as is

**Comment by getBoolean** [comment]
> Okay so we'll leave it as is

I'll undo the code related to that.

**Comment by alexrabin** [comment]
Can you update the version number to 0.0.3+2 and add to the change log please? Don't forget to give yourself a mention 😁

**Comment by getBoolean** [comment]
> Can you update the version number to 0.0.3+2 and add to the change log please? Don't forget to give yourself a mention 😁

Before I do that, should we keep forcing the file to be categorized as file if its specific type isn't enabled? Now that it will always be uploaded if there is a correct item, the categorization might come off as inconsistent to the programmer. I think it would be better to remove that

Either way, we should document that image, video, pdf, and audio will be included by file

**Comment by alexrabin** [comment]
I still think we need the isAllowed because if you add in a text and video and the video isn't going to be handled at all, the video is still saved to the device using up space for no reason

**Comment by alexrabin** [comment]
I say we had a Boolean then. Types that aren't defined shouldn't be added

**Comment by getBoolean** [comment]
> I say we had a Boolean then. Types that aren't defined shouldn't be added

Sounds good

**Comment by alexrabin** [comment]
Do you have any other changes before I merge?

**Comment by getBoolean** [comment]
> Do you have any other changes before I merge?

I am working on the boolean flag.

Also what do you think about this? https://github.com/alexrabin/FlutterNativeDragAndDrop/pull/5#issuecomment-1020620429

**Comment by alexrabin** [comment]
Well with the new Boolean flag to only allow the types specified what do you think the best course of action is?

**Comment by getBoolean** [comment]
> Well with the new Boolean flag to only allow the types specified what do you think the best course of action is?

I think that the programmer may expect PDFs to always be categorized as DropDataType.pdf, but it's also possible another programmer will not expect anything to be categorized as DropDataType.pdf since they have only allowed DropDataType.file.

If more file types are added, the files may suddenly get categorized differently after an update, which may break things. Because of that, I think that forcing categorizing it as a file is the best option

**Comment by getBoolean** [comment]
> I say we had a Boolean then. Types that aren't defined shouldn't be added

Should the default for `receiveNonAllowedItems` be true or false? Also is this name okay? It sounds a little ambiguous to me.

**Comment by alexrabin** [comment]
So when you have the pdf data type enabled and the file data type enabled and add pdf file then the pdf file will be assigned the file data type?

**Comment by getBoolean** [comment]
> So alwhen you had the pdf data type enabled and the file data type enabled a pdf file will be assigned the file data type?

When PDF and FILE are enabled, it is categorized as PDF

**Comment by alexrabin** [comment]
Okay okay yep go forth and do what you must 😉

**Comment by alexrabin** [comment]
Looks great. Can you update the version and change log by chance?

**Comment by getBoolean** [comment]
> Looks great. Can you update the version and change log by chance?

Sure

**Comment by getBoolean** [comment]
Alright that should be it!

**Comment by alexrabin** [comment]
@getBoolean Is there a way I can reach out to you directly? I feel like it would be more efficient if we continue to work on this together

**Comment by getBoolean** [comment]
> @getBoolean Is there a way I can reach out to you directly? I feel like it would be more efficient if we continue to work on this together. If not just dislike this comment

Sure, my discord is Boolean#9224

**Pull request merged**
